Warehouse/Warehouse/Models/Remittance.cs
namespace Warehouse.Models
{
    using System;
    using System.Collections.Generic;
    using Warehouse.Entities;

    public class Remittance : EntityBase
    {
        public string Code { get; set; }

        public RemittanceType RemittanceType { get; set; }
        
        public DateTime InDate { get; set; } = DateTime.Now;

        public long StoreId { get; set; }

        public virtual Store Store { get; set; }

        public long UserId { get; set; }

        public virtual User User { get; set; }

        public string Description { get; set; }

        public virtual ICollection<RemittanceStuff> RemittanceStuffs { get; set; }

        public Guid InstanceId { get; set; }
    }
}

Warehouse/Warehouse/Models/RemittanceType.cs
namespace Warehouse.Models
{
    public enum RemittanceType : byte
    {
        IncomingTransfer = 1,
        Withdrawal
    }
}

Warehouse/Warehouse/Controllers/RemittanceStuffsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Warehouse.Models;

namespace Warehouse.Controllers
{
    public class RemittanceStuffsController : Controller
    {
        private readonly WarehouseContext _context;

        private static long _remittanceId;

        public RemittanceStuffsController(WarehouseContext context)
        {
            _context = context;
        }

        // GET: RemittanceStuffs
        public async Task<IActionResult> Index(long Id)
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }

            _remittanceId = Id;

            var warehouseContext = _context.RemittanceStuffs.Include(r => r.Remittance).Include(r => r.Stuff);
            return View(await warehouseContext.ToListAsync());
        }

        // GET: RemittanceStuffs/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }

            if (id == null)
            {
                return NotFound();
            }

            var remittanceStuff = await _context.RemittanceStuffs
                .Include(r => r.Remittance)
                .Include(r => r.Stuff)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (remittanceStuff == null)
            {
                return NotFound();
            }

            return View(remittanceStuff);
        }

        // GET: RemittanceStuffs/Create
        public IActionResult Create()
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }

            ViewData["RemittanceId"] = new SelectList(_context.Remittances, "Id", "Code");
            ViewData["StuffId"] = new SelectList(_context.Stuffs, "Id", "Code");
            return View();
        }

        // POST: RemittanceStuffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RemittanceId,StuffId,Count,InstanceId,Id")] RemittanceStuff remittanceStuff)
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }

            remittanceStuff.RemittanceId = _remittanceId;
            remittanceStuff.Count = remittanceStuff.Count <= 0 ? 1 : remittanceStuff.Count;

            if (ModelState.IsValid)
            {
                _context.Add(remittanceStuff);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RemittanceId"] = new SelectList(_context.Remittances, "Id", "Code", remittanceStuff.RemittanceId);
            ViewData["StuffId"] = new SelectList(_context.Stuffs, "Id", "Code", remittanceStuff.StuffId);
            return View(remittanceStuff);
        }

        // GET: RemittanceStuffs/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }

            if (id == null)
            {
                return NotFound();
            }

            var remittanceStuff = await _context.RemittanceStuffs.FindAsync(id);
            if (remittanceStuff == null)
            {
                return NotFound();
            }
            ViewData["RemittanceId"] = new SelectList(_context.Remittances, "Id", "Code", remittanceStuff.RemittanceId);
            ViewData["StuffId"] = new SelectList(_context.Stuffs, "Id", "Code", remittanceStuff.StuffId);
            return View(remittanceStuff);
        }

        // POST: RemittanceStuffs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("RemittanceId,StuffId,Count,InstanceId,Id")] RemittanceStuff remittanceStuff)
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }

            if (id != remittanceStuff.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(remittanceStuff);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RemittanceStuffExists(remittanceStuff.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RemittanceId"] = new SelectList(_context.Remittances, "Id", "Code", remittanceStuff.RemittanceId);
            ViewData["StuffId"] = new SelectList(_context.Stuffs, "Id", "Code", remittanceStuff.StuffId);
            return View(remittanceStuff);
        }

        // GET: RemittanceStuffs/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }

            if (id == null)
            {
                return NotFound();
            }

            var remittanceStuff = await _context.RemittanceStuffs
                .Include(r => r.Remittance)
                .Include(r => r.Stuff)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (remittanceStuff == null)
            {
                return NotFound();
            }

            return View(remittanceStuff);
        }

        // POST: RemittanceStuffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }

            var remittanceStuff = await _context.RemittanceStuffs.FindAsync(id);
            _context.RemittanceStuffs.Remove(remittanceStuff);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RemittanceStuffExists(long id)
        {
            return _context.RemittanceStuffs.Any(e => e.Id == id);
        }

        private bool IsUserAdmin()
        {
            HttpContext.Session.TryGetValue("IUI", out byte[] session);
            string currentUserId = session.LastOrDefault().ToString();

            return Convert.ToInt64(currentUserId) == 1;
        }
    }
}

Warehouse/Warehouse/Controllers/RemittancesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Warehouse.Models;

namespace Warehouse.Controllers
{
    public class RemittancesController : Controller
    {
        private readonly WarehouseContext _context;

        public RemittancesController(WarehouseContext context)
        {
            _context = context;
        }

        // GET: Remittances
        public async Task<IActionResult> Index()
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }


            var warehouseContext = _context.Remittances.Include(r => r.Store).Include(r => r.User);
            return View(await warehouseContext.ToListAsync());
        }

        // GET: Remittances/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }
            
            if (id == null)
            {
                return NotFound();
            }

            var remittance = await _context.Remittances
                .Include(r => r.Store)
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (remittance == null)
            {
                return NotFound();
            }

            return View(remittance);
        }

        // GET: Remittances/Create
        public IActionResult Create()
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }

            ViewData["StoreId"] = new SelectList(_context.Store, "Id", "Name");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Password");
            return View();
        }

        // POST: Remittances/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Code,RemittanceType,InDate,StoreId,UserId,Description,InstanceId,Id")] Remittance remittance)
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }

            HttpContext.Session.TryGetValue("IUI", out byte[] session);
            string currentUserId = session.LastOrDefault().ToString();

            remittance.UserId = Convert.ToInt64(currentUserId);

            remittance.InDate = DateTime.Now;
            remittance.StoreId = 1;

            if (ModelState.IsValid)
            {
                _context.Add(remittance);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StoreId"] = new SelectList(_context.Store, "Id", "Name", remittance.StoreId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Password", remittance.UserId);
            return View(remittance);
        }

        // GET: Remittances/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }

            if (id == null)
            {
                return NotFound();
            }

            var remittance = await _context.Remittances.FindAsync(id);
            if (remittance == null)
            {
                return NotFound();
            }
            ViewData["StoreId"] = new SelectList(_context.Store, "Id", "Name", remittance.StoreId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Password", remittance.UserId);
            return View(remittance);
        }

        // POST: Remittances/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Code,RemittanceType,InDate,StoreId,UserId,Description,InstanceId,Id")] Remittance remittance)
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }

            if (id != remittance.Id)
            {
                return NotFound();
            }

            HttpContext.Session.TryGetValue("IUI", out byte[] session);
            string currentUserId = session.LastOrDefault().ToString();

            remittance.UserId = Convert.ToInt64(currentUserId);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(remittance);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RemittanceExists(remittance.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StoreId"] = new SelectList(_context.Store, "Id", "Name", remittance.StoreId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Password", remittance.UserId);
            return View(remittance);
        }

        // GET: Remittances/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }

            if (id == null)
            {
                return NotFound();
            }

            var remittance = await _context.Remittances
                .Include(r => r.Store)
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (remittance == null)
            {
                return NotFound();
            }

            return View(remittance);
        }

        // POST: Remittances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (!IsUserAdmin())
            {
                return RedirectToAction("Error", "Home");
            }

            var remittance = await _context.Remittances.FindAsync(id);
            _context.Remittances.Remove(remittance);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RemittanceExists(long id)
        {
            return _context.Remittances.Any(e => e.Id == id);
        }

        private bool IsUserAdmin()
        {
            HttpContext.Session.TryGetValue("IUI", out byte[] session);
            string currentUserId = session.LastOrDefault().ToString();

            return Convert.ToInt64(currentUserId) == 1;
        }
    }
}

Warehouse/Warehouse/Views/Remittances/Create.cshtml
@model Warehouse.Models.Remittance

@{
	ViewData["Title"] = "حواله جدید";
}

<h4>ثبت حواله جدید</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Code" class="control-label"></label>
				<input asp-for="Code" class="form-control" />
				<span asp-validation-for="Code" class="text-danger"></span>
			</div>
			<div class="form-group">
				@*<label asp-for="RemittanceType" class="control-label"></label>
					<select asp-for="RemittanceType" class="form-control"></select>
					<span asp-validation-for="RemittanceType" class="text-danger"></span>*@
				<select asp-for="RemittanceType" class="form-control"
						asp-items="Html.GetEnumSelectList<RemittanceType>()">
					<option selected="selected" value="">انتخاب کنید ...</option>
				</select>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label"></label>
				<input asp-for="Description" class="form-control" />
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="ثبت" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">بازگشت</a>
</div>

Warehouse/Warehouse/Views/Remittances/Delete.cshtml
@model Warehouse.Models.Remittance

@{
    ViewData["Title"] = "حذف حواله";
}

<h3>آیا اطمینان از حذف دارید?</h3>
<div>
    <h4>حذف حواله</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            کد
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            نوع
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RemittanceType)
        </dd>
        <dt class = "col-sm-2">
            تاریخ
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InDate)
        </dd>
        <dt class = "col-sm-2">
            شرح
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="حذف" class="btn btn-danger" /> |
        <a asp-action="Index">بازگشت</a>
    </form>
</div>

Warehouse/Warehouse/Views/Remittances/Details.cshtml
@model Warehouse.Models.Remittance

@{
    ViewData["Title"] = "جزئیات";
}

<div>
    <h4>حواله</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            کد
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            نوع حواله
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RemittanceType)
        </dd>
        <dt class = "col-sm-2">
            تاریخ
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InDate)
        </dd>
        <dt class = "col-sm-2">
            شرح
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">ویرایش</a> |
    <a asp-action="Index">بازگشت</a>
</div>

Warehouse/Warehouse/Views/Remittances/Edit.cshtml
@model Warehouse.Models.Remittance

@{
	ViewData["Title"] = "ویرایش";
}

<h4>ویرایش حواله</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Code" class="control-label"></label>
				<input asp-for="Code" class="form-control" />
				<span asp-validation-for="Code" class="text-danger"></span>
			</div>
			<div class="form-group">
				@*<label asp-for="RemittanceType" class="control-label"></label>
					<select asp-for="RemittanceType" class="form-control"></select>
					<span asp-validation-for="RemittanceType" class="text-danger"></span>*@

				<select asp-for="RemittanceType" class="form-control"
						asp-items="Html.GetEnumSelectList<RemittanceType>()">
					<option selected="selected" value="">انتخاب کنید ...</option>
				</select>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label"></label>
				<input asp-for="Description" class="form-control" />
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>
			<input type="hidden" asp-for="Id" />
			<div class="form-group">
				<input type="submit" value="ثبت" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">بازگشت</a>
</div>

Warehouse/Warehouse/Views/Remittances/Index.cshtml
@model IEnumerable<Warehouse.Models.Remittance>

@{
	ViewData["Title"] = "حواله انبار";
}

<h1>حواله ورود/خروج</h1>

<p>
	<a asp-action="Create">جدید</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>
				کد
			</th>
			<th>
				نوع حواله
			</th>
			<th>
				تاریخ
			</th>
			<th>
				شرح
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Code)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.RemittanceType)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.InDate)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Description)
				</td>
				<td>
					<a asp-action="Edit" asp-route-id="@item.Id">ویرایش</a> |
					<a asp-action="Details" asp-route-id="@item.Id">جزئیات</a> |
					<a asp-action="Delete" asp-route-id="@item.Id">حذف</a> |
					<a asp-controller="RemittanceStuffs" asp-action="Index" asp-route-id="@item.Id">اقلام</a>
				</td>
			</tr>
		}
	</tbody>
</table>